# Generated by Django 5.2.6 on 2025-11-04 05:46

import django.db.models.deletion
import django.utils.timezone
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kpfa', '0011_order_full_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('naira_card', 'Naira Card'), ('opay', 'Opay'), ('moniepoint', 'Moniepoint'), ('mtn_momo', 'MTN MoMo Ghana'), ('bank_transfer', 'Bank Transfer'), ('cod', 'Cash on Delivery')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('reference', models.CharField(default=payments.models.generate_reference, max_length=64, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=128, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='kpfa.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['reference'], name='payments_pa_referen_75358f_idx'), models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx')],
            },
        ),
    ]
