# Generated by Django 5.2.6 on 2025-11-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
