# Generated by Django 5.2.6 on 2025-11-07 04:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpfa', '0011_order_full_name'),
        ('payments', '0002_alter_payment_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('method', models.CharField(choices=[('OPAY', 'Opay'), ('BANK', 'Bank Transfer')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='kpfa.candidate')),
            ],
        ),
    ]
