# Generated by Django 5.2.6 on 2025-10-23 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpfa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('team_type', models.CharField(choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('JUNIOR', 'Junior'), ('OPPONENT', 'Opponent')], max_length=10)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('coach_name', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('is_kpfa_team', models.BooleanField(default=True, help_text='Mark as True if this is a KPFA team')),
            ],
        ),
        migrations.CreateModel(
            name='MenPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('position', models.CharField(max_length=50)),
                ('shirt_number', models.CharField(blank=True, max_length=5, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('state_of_origin', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='men_player_profiles/')),
                ('guardian_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('guardian_address', models.TextField(blank=True, max_length=300, null=True)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='men_players', to='kpfa.team')),
            ],
        ),
    ]
