# Generated by Django 5.2.6 on 2025-10-23 10:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpfa', '0003_juniorplayer_womenplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(default=django.utils.timezone.now)),
                ('match_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('competition_type', models.CharField(choices=[('FRIENDLY', 'Friendly'), ('LEAGUE', 'League'), ('TOURNAMENT', 'Tournament'), ('OTHER', 'Other')], default='FRIENDLY', max_length=20)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='match_banners/')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='kpfa.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='kpfa.team')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='kpfa.country')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('position', models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('RCB', 'Right Center Back'), ('LCB', 'Left Center Back'), ('RWB', 'Right Wing Back'), ('LWB', 'Left Wing Back'), ('AM', 'Attacking Midfielder'), ('DM', 'Defensive Midfielder'), ('RWF', 'Right Wing Forward'), ('LWF', 'Left Wing Forward'), ('STK', 'Striker')], max_length=5, null=True)),
                ('phone_country_code', models.CharField(choices=[('+233', '🇬🇭 Ghana (+233)'), ('+234', '🇳🇬 Nigeria (+234)'), ('+225', '🇨🇮 Ivory Coast (+225)'), ('+221', '🇸🇳 Senegal (+221)')], default='+233', max_length=5)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{5,15}$', 'Enter a valid phone number.')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='candidate_profiles/')),
                ('guardian_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_contact_code', models.CharField(blank=True, choices=[('+233', '🇬🇭 Ghana (+233)'), ('+234', '🇳🇬 Nigeria (+234)'), ('+225', '🇨🇮 Ivory Coast (+225)'), ('+221', '🇸🇳 Senegal (+221)')], default='+233', max_length=5, null=True)),
                ('guardian_contact_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{5,15}$', 'Enter a valid phone number.')])),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('guardian_address', models.TextField(blank=True, max_length=300, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpfa.team')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpfa.country')),
                ('state_of_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpfa.state')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
