# Generated by Django 5.2.6 on 2025-10-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpfa', '0004_contact_country_match_state_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
