# Generated by Django 5.2.6 on 2025-10-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpfa', '0006_order_email_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH_ON_DELIVERY', 'Cash on Delivery')], default='BANK_TRANSFER', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, help_text='Upload bank transfer receipt (max 2MB, JPG/PNG only).', null=True, upload_to='order_proofs/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
