# Generated by Django 5.2.6 on 2025-10-28 02:19

import kpfa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpfa', '0007_order_payment_method_order_payment_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, help_text='Upload bank transfer receipt (max 2MB, JPG/PNG only).', null=True, upload_to='order_proofs/', validators=[kpfa.models.Order.validate_payment_proof]),
        ),
    ]
