# Generated by Django 5.2.6 on 2025-10-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpfa', '0008_alter_order_payment_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('COD', 'Cash on Delivery')], default='BANK_TRANSFER', max_length=20),
        ),
    ]
