# Generated by Django 5.2.6 on 2025-11-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpfa', '0010_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
