# Generated by Django 5.2.6 on 2025-11-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpfa', '0011_order_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=10),
        ),
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('NOT_PAID', 'Not Paid'), ('PAID', 'Paid'), ('UNDER_REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='NOT_PAID', max_length=20),
        ),
    ]
